// <auto-generated />
using System;
using Education_assistant.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education_assistant.Models
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Education_assistant.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("hoc_phi");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<int?>("LoaiBangCap")
                        .HasColumnType("int")
                        .HasColumnName("loai_bang_cap");

                    b.Property<string>("MaChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_chuong_trinh");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_chuong_trinh");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("thoi_gian");

                    b.Property<int>("TongSoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("tong_so_tin_chi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("chuong_trinh_dao_tao");
                });

            modelBuilder.Entity("Education_assistant.Models.DangKyMonHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Diem")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("diem");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("LopHocPhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<DateTime>("NgayDangKyHoc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_dang_ky_hoc");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("dang_ky_mon_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.DiemSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiemChuyenCan")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("diem_chuyen_can");

                    b.Property<decimal>("DiemThi")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("diem_thi");

                    b.Property<decimal>("DiemTongKet")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("diem_tong_ket");

                    b.Property<decimal>("DiemTrungBinh")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("diem_trung_binh");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ghi_chu");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<Guid?>("HocKyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("hoc_ky_id");

                    b.Property<Guid?>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_them");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("diem_so");
                });

            modelBuilder.Entity("Education_assistant.Models.DiemTong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("DiemTongKet")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("diem_tong_ket");

                    b.Property<Guid?>("HocKyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("hoc_ky_id");

                    b.Property<int?>("LoaiMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("loai");

                    b.Property<Guid?>("LopHocPhanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_phan_id");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<Guid?>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<int>("TinChi")
                        .HasColumnType("int")
                        .HasColumnName("tin_chi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("diem_tong");
                });

            modelBuilder.Entity("Education_assistant.Models.GiangVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("longtext")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cccd");

                    b.Property<int>("ChucVu")
                        .HasColumnType("int")
                        .HasColumnName("chuc_vu");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("chuyen_nganh");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiaChi")
                        .HasColumnType("longtext")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime?>("NgayVaoTruong")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_vao_truong");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<Guid?>("TaiKhoanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tai_khoan_id");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trinh_do");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId")
                        .IsUnique();

                    b.ToTable("giang_vien");
                });

            modelBuilder.Entity("Education_assistant.Models.HoSoHocTap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChuongTrinhDaoTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("chuong_trinh_dao_tao_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("gpa");

                    b.Property<DateTime?>("NgayNhapHoc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_nhap_hoc");

                    b.Property<DateTime?>("NgayTotNghiep")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tot_nghiep");

                    b.Property<Guid?>("SinhVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("sinh_vien_id");

                    b.Property<int>("TinChi")
                        .HasColumnType("int")
                        .HasColumnName("tin_chi");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int")
                        .HasColumnName("tinh_trang");

                    b.Property<bool>("TotNghiep")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("tot_nghiep");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ChuongTrinhDaoTaoId")
                        .IsUnique();

                    b.HasIndex("SinhVienId")
                        .IsUnique();

                    b.ToTable("ho_so_hoc_tap");
                });

            modelBuilder.Entity("Education_assistant.Models.HocKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("MaHocKy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_hoc_ky");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nam_hoc");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime?>("NgayBatDauDangky")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_bat_dau_dang_ky");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<DateTime?>("NgayKetThucDangKy")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ket_thuc_dang_ky");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_hoc_ky");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("hoc_ky");
                });

            modelBuilder.Entity("Education_assistant.Models.Khoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_khoa");

                    b.Property<Guid?>("TruongId")
                        .HasColumnType("char(36)")
                        .HasColumnName("truong_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViTriPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_tri_phong");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("TruongId");

                    b.ToTable("khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_lop_hoc");

                    b.Property<int>("SiSo")
                        .HasColumnType("int")
                        .HasColumnName("si_so");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("nam_hoc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.ToTable("lop_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHocPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<Guid?>("HocKyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("hoc_ky_id");

                    b.Property<string>("MaHocPhan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_hoc_phan");

                    b.Property<Guid?>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phong_hoc");

                    b.Property<int>("SiSo")
                        .HasColumnType("int")
                        .HasColumnName("si_so");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MonHocId");

                    b.ToTable("lop_hoc_phan");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<int?>("LoaiMonHoc")
                        .HasColumnType("int")
                        .HasColumnName("loai");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_mon_hoc");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mo_ta");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int")
                        .HasColumnName("so_tiet");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("so_tin_chi");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_mon_hoc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("mon_hoc");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHocDaoTao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DaoTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dao_tao_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("MonHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mon_hoc_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DaoTaoId");

                    b.HasIndex("MonHocId");

                    b.ToTable("mon_hoc_dao_tao");
                });

            modelBuilder.Entity("Education_assistant.Models.QuaTrinhCongTac", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("CongTac")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("cong_tac");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GiangVienId")
                        .HasColumnType("char(36)")
                        .HasColumnName("giang_vien_id");

                    b.Property<Guid?>("KhoaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("khoa_id");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("luong");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_tri");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("KhoaId");

                    b.ToTable("QuaTrinhCongTacs");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("anh_dai_dien");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cccd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DaoTaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("dao_tao_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int")
                        .HasColumnName("gioi_tinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ho_ten");

                    b.Property<Guid?>("LopHocId")
                        .HasColumnType("char(36)")
                        .HasColumnName("lop_hoc_id");

                    b.Property<int>("MSSV")
                        .HasColumnType("int")
                        .HasColumnName("mssv");

                    b.Property<DateTime>("NgayNhapHoc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_nhap_hoc");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime>("NgayTotNghiep")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_tot_nghiep");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DaoTaoId");

                    b.HasIndex("LopHocId");

                    b.ToTable("sinh_vien");
                });

            modelBuilder.Entity("Education_assistant.Models.TaiKhoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ngay_dang_nhap");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("reset_token");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reset_expires");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("trang_thai");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("tai_khoan");
                });

            modelBuilder.Entity("Education_assistant.Models.Truong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("MaTruong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ma_truong");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenTruong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ten_truong");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_tri");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.ToTable("truong");
                });

            modelBuilder.Entity("Education_assistant.Models.ChuongTrinhDaoTao", b =>
                {
                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany("DanhSachChuongTrinhDaoTao")
                        .HasForeignKey("KhoaId");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.DangKyMonHoc", b =>
                {
                    b.HasOne("Education_assistant.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachDangKyMonHoc")
                        .HasForeignKey("LopHocPhanId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachDangKyMonHoc")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.DiemSo", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId");

                    b.HasOne("Education_assistant.Models.HocKy", "HocKy")
                        .WithMany("DanhSachDiemSo")
                        .HasForeignKey("HocKyId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachDiemSo")
                        .HasForeignKey("MonHocId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachDiemSo")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.DiemTong", b =>
                {
                    b.HasOne("Education_assistant.Models.HocKy", "HocKy")
                        .WithMany("DanhSachDiemTong")
                        .HasForeignKey("HocKyId");

                    b.HasOne("Education_assistant.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DanhSachDiemTong")
                        .HasForeignKey("LopHocPhanId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachDiemTong")
                        .HasForeignKey("MonHocId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithMany("DanhSachDiemTong")
                        .HasForeignKey("SinhVienId");

                    b.Navigation("HocKy");

                    b.Navigation("LopHocPhan");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.GiangVien", b =>
                {
                    b.HasOne("Education_assistant.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiangVien")
                        .HasForeignKey("Education_assistant.Models.GiangVien", "TaiKhoanId");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Education_assistant.Models.HoSoHocTap", b =>
                {
                    b.HasOne("Education_assistant.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithOne("HoSoHocTap")
                        .HasForeignKey("Education_assistant.Models.HoSoHocTap", "ChuongTrinhDaoTaoId");

                    b.HasOne("Education_assistant.Models.SinhVien", "SinhVien")
                        .WithOne("HoSoHocTap")
                        .HasForeignKey("Education_assistant.Models.HoSoHocTap", "SinhVienId");

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.Khoa", b =>
                {
                    b.HasOne("Education_assistant.Models.Truong", "Truong")
                        .WithMany("DanhSachKhoa")
                        .HasForeignKey("TruongId");

                    b.Navigation("Truong");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHoc", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachLopHoc")
                        .HasForeignKey("GiangVienId");

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHocPhan", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("Education_assistant.Models.HocKy", "HocKy")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("HocKyId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachLopHocPhan")
                        .HasForeignKey("MonHocId");

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHoc", b =>
                {
                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany("DanhSachMonHoc")
                        .HasForeignKey("KhoaId");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHocDaoTao", b =>
                {
                    b.HasOne("Education_assistant.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("DanhSachMonHocDaoTao")
                        .HasForeignKey("DaoTaoId");

                    b.HasOne("Education_assistant.Models.MonHoc", "MonHoc")
                        .WithMany("DanhSachMonHocDaoTao")
                        .HasForeignKey("MonHocId");

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.QuaTrinhCongTac", b =>
                {
                    b.HasOne("Education_assistant.Models.GiangVien", "GiangVien")
                        .WithMany("DanhSachCongTac")
                        .HasForeignKey("GiangVienId");

                    b.HasOne("Education_assistant.Models.Khoa", "Khoa")
                        .WithMany("DanhSachQuaTrinhCongTac")
                        .HasForeignKey("KhoaId");

                    b.Navigation("GiangVien");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVien", b =>
                {
                    b.HasOne("Education_assistant.Models.ChuongTrinhDaoTao", "ChuongTrinhDaoTao")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("DaoTaoId");

                    b.HasOne("Education_assistant.Models.LopHoc", "LopHoc")
                        .WithMany("DanhSachSinhVien")
                        .HasForeignKey("LopHocId");

                    b.Navigation("ChuongTrinhDaoTao");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("Education_assistant.Models.ChuongTrinhDaoTao", b =>
                {
                    b.Navigation("DanhSachMonHocDaoTao");

                    b.Navigation("DanhSachSinhVien");

                    b.Navigation("HoSoHocTap");
                });

            modelBuilder.Entity("Education_assistant.Models.GiangVien", b =>
                {
                    b.Navigation("DanhSachCongTac");

                    b.Navigation("DanhSachLopHoc");

                    b.Navigation("DanhSachLopHocPhan");
                });

            modelBuilder.Entity("Education_assistant.Models.HocKy", b =>
                {
                    b.Navigation("DanhSachDiemSo");

                    b.Navigation("DanhSachDiemTong");

                    b.Navigation("DanhSachLopHocPhan");
                });

            modelBuilder.Entity("Education_assistant.Models.Khoa", b =>
                {
                    b.Navigation("DanhSachChuongTrinhDaoTao");

                    b.Navigation("DanhSachMonHoc");

                    b.Navigation("DanhSachQuaTrinhCongTac");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHoc", b =>
                {
                    b.Navigation("DanhSachSinhVien");
                });

            modelBuilder.Entity("Education_assistant.Models.LopHocPhan", b =>
                {
                    b.Navigation("DanhSachDangKyMonHoc");

                    b.Navigation("DanhSachDiemTong");
                });

            modelBuilder.Entity("Education_assistant.Models.MonHoc", b =>
                {
                    b.Navigation("DanhSachDiemSo");

                    b.Navigation("DanhSachDiemTong");

                    b.Navigation("DanhSachLopHocPhan");

                    b.Navigation("DanhSachMonHocDaoTao");
                });

            modelBuilder.Entity("Education_assistant.Models.SinhVien", b =>
                {
                    b.Navigation("DanhSachDangKyMonHoc");

                    b.Navigation("DanhSachDiemSo");

                    b.Navigation("DanhSachDiemTong");

                    b.Navigation("HoSoHocTap");
                });

            modelBuilder.Entity("Education_assistant.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("Education_assistant.Models.Truong", b =>
                {
                    b.Navigation("DanhSachKhoa");
                });
#pragma warning restore 612, 618
        }
    }
}
